### ISSUE TITLE
[GW] 홈 화면에서 필요한 API 스펙 정의 with Menu팀

### ISSUE THREAD

**Issue by SeungGun** [HeeHeePresso/Backend#49]
제가 PR #46 에 코멘트 달았던 것을 바탕으로 여기서 논의드립니다. @yoon-chaejin 

홈 화면에서 제공할 메뉴 목록을 위한 API를 메뉴 서비스 팀에게 스펙 요청 드립니다. 
다른 의견 있으시면 코멘트 부탁드려요!

### 기능
메뉴 ID 목록으로 메뉴 정보 목록 조회

### 데이터 교환
- 게이트웨이 → 메뉴
  - `List<Long>`: 메뉴 ID 목록
- 게이트웨이 ← 메뉴
  - `List<MenuInfo>` : 메뉴 정보 목록 (타입 MenuInfo와 아래 필드와 같은 네이밍은 예시일 뿐 별도로 지정해주셔도됩니다.)

> MenuInfo Spec
```json
 {
      "menuInfo": {
         "menuId" : "메뉴 ID",
         "name" : "메뉴 이름",
         "price" : "메뉴 가격",
         "thumbnailImage" : "메뉴 썸네일 이미지 path"
      }
 }
 ```

**Comment by yoon-chaejin** [comment]
@SeungGun 님, 의견 감사합니다.
PR 리뷰 내용 중 @jjh5887 님이 주신 [의견](https://github.com/HeeHeePresso/Backend/pull/47#discussion_r1551103190)을 추가해서 아래와 같이 layout 잡아보려고 합니다.

| 항목 | 데이터 | 예시 | 비고 |
| -- | -- | -- | -- |
| HTTP Method 및 경로 | GET /menus |  |  |
| Path Variable | 없음 |  |  |
| Request Param | id | id=1&id=2&id=3 | 동일한 Param명으로 전달주시면 List 형태로 Param을 받을 수 있다고 합니다. |
| Request Body | 없음 |  |  |
| Response Body | 하단 참고 | 하단 참고 | resultCode 및 resultMessage 는 별도 공유 예정 |

``` json
{
    "resultCode" : "API 결과 코드", 
    "resultMessage" : "API 결과 메시지", 
    "data" : [{
        "id" : "메뉴 ID",
        "name" : "메뉴 이름",
        "price" : "메뉴 가격",
        "thumbnailImageUrl" : "메뉴 썸네일 이미지 path"
    }]
}
```

``` json
{
    "resultCode" : 0, 
    "resultMessage" : "성공", 
    "data" : [{
        "id" : 1,
        "name" : "메뉴01",
        "price" : "2500",
        "thumbnailImageUrl" : "https://github.com/HeeHeePresso/Backend/assets/49651099/58dca505-0a34-4926-a0aa-336a91c864c9"
    }, {
        "id" : 2
        "name" : "메뉴02",
        "price" : "3000",
        "thumbnailImageUrl" : "https://github.com/HeeHeePresso/Backend/assets/49651099/2ba003c2-ddd6-41cf-bb7e-e3a18b7e2eec"
    }]
}
```

**Comment by yoon-chaejin** [comment]
위 내용에 대해 아래 커밋으로 반영해서 Review 재요청했습니다.

[7f15305](https://github.com/HeeHeePresso/Backend/pull/47/commits/7f153055b241ead41493dc12401a64c3787face8)
[Menu] Review 반영 - Response Object 사용

ApiResponse : Response Object, 결과코드 및 결과메시지를 전달
GetMenusResponse : 화면에서 필요한 정보만 전달
